title: Shreesh Roliwal
author: GitHub User
email: sroliwal@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  I am a Student / Reverse Engineer and CTF Player
  and a Hobbiest Malware Analyst
  Contact Discord karmaX#1165
show_excerpts: true # set to true to show excerpts on the homepage

paginate: 4
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/karmaX8080
      icon: twitter
      color: cyan
    - url: https://github.com/shreesh1
      icon: github
      color: purple
    - url: https://www.linkedin.com/in/shreesh-roliwal-2677ba183/
      color: green
      icon: linkedin-in

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain
